### PR TITLE
Web obt

### PR DESCRIPTION
**Pull request by khaefner**
We will need to work through iotivity.py and oc_python.c to address the conflicts.   
@FrankZRS I'll work with you to address the conflicts here.

### CODE REVIEW

**Comment by FrankZRS** [comment]
Apologies Kyle, I wasn't aware that someone else is also working with iotivity.py and oc_python.c, so it looks like both of us have modified existing code and added new functions. 

Here's a summary of what I've done: 
1. Added new functions for connecting cloud_proxy to plgd cloud, and proxying Cascoda's chips to the cloud. 
2. Added retransmissions to all existing functions in iotivity.py that I used during the connecting and proxying process (e.g. discover_resources() which we both used). This does nothing else than resending a request a few times if the first attempt fails, so I think it shouldn't affect your usage of these functions. 
3. Added a global bool variable in oc_python.c that stores the result of a transmission. This is changed in every callback functions where responses from the device are handled. iotivity.py retrieves this variable, and does the retransmissions if the value is false (transmission failed). 

It would be nice if you can have a look and reconcile some of these conflicts, I'm happy to make changes to my code at your request :)

**Comment by khaefner** [comment]
~format

**Comment by WAvdBeek** [comment]
~format

**Comment by khaefner** [comment]
> Hi Kyle,
> 
> did you make another repo and referenced that one?
> 
> Disabling automatic garbage collection Setting up auth Fetching the repository /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/web-obt*:refs/remotes/origin/web-obt* +refs/tags/web-obt*:refs/tags/web-obt* The process '/usr/bin/git' failed with exit code 1 Waiting 19 seconds before trying again /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/web-obt*:refs/remotes/origin/web-obt* +refs/tags/web-obt*:refs/tags/web-obt* The process '/usr/bin/git' failed with exit code 1 Waiting 13 seconds before trying again /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/web-obt*:refs/remotes/origin/web-obt* +refs/tags/web-obt*:refs/tags/web-obt* Error: The process '/usr/bin/git' failed with exit code 1

There was a cablelabs repo that this was largely developed in then I moved things over.  I am not sure where the reference is, any ideas on how I fix it?

**Comment by khaefner** [comment]
@FrankZRS The changes you made are fine....I merged your PR.

**Review by WAvdBeek — APPROVED** [review]

**Comment by WAvdBeek** [comment]
~format

**Pull request merged**
