### PR TITLE
fix: remove links to the deleted resource from the collections

### PR DESCRIPTION
**Pull request by jkralik**

### CODE REVIEW

**Comment by Danielius1922** [comment]
Good job, a deleted resource should now be removed from all collections it was linked to. :+1: 

Although I would add a unit test that verifies the scenario described by Jonas Andersson:
1) create resource by oc_new_resource
2) link it one or more collection
3) delete the resource and check that it was removed from all collections

**Review by Danielius1922 — APPROVED** [review]

**Comment by jkralik** [comment]
> Good job, a deleted resource should now be removed from all collections it was linked to. 👍
> 
> Although I would add a unit test that verifies the scenario described by Jonas Andersson:
> 
> 1. create resource by oc_new_resource
> 2. link it one or more collection
> 3. delete the resource and check that it was removed from all collections

Adde test :)

**Review by ondrejtomcik — APPROVED** [review]

**Comment by jkralik** [comment]
@SiMet please could you run the OCF test with this PR?

**Comment by jkralik** [comment]
@WAvdBeek could we merge this fix? the master branch currently leaks memory.

**Comment by SiMet** [comment]
> @SiMet please could you run the OCF test with this PR?

Started... results should be in 3 hours

**Review by WAvdBeek — APPROVED** [review]

**Comment by SiMet** [comment]
> > @SiMet please could you run the OCF test with this PR?
> 
> Started... results should be in 3 hours

All testcases passed.

**Pull request merged**
