### PR TITLE
Fix issue oic/d piid issue with notification (#40)

### PR DESCRIPTION
**Pull request by Danielius1922**
When generating the representation for the /oic/d
resource the getter checks the endpoint_t version
provided as argument to the call. If the endpoint
is NULL or has an old version the piid field
is skipped.
When sending observation messages NULL was used
as the endpoint value, therefore the piid field
was never present in the notifications.

The issue is fixed by taking the endpoint value
from the currently handled observer.

### CODE REVIEW

**Comment by Danielius1922** [comment]
@jkralik for whatever reason this test sometimes fails, last time my PR was merged and it happened now:

```
--- FAIL: TestClientGetDeviceByIPWithIP6 (10.00s)
panic: (Internal) no response from the device ef4bf406-4fcf-466b-49b9-6161abbf0fe4 [recovered]
	panic: (Internal) no response from the device ef4bf406-4fcf-466b-49b9-6161abbf0fe4

goroutine 65 [running]:
testing.tRunner.func1.2(0x8faea0, 0xc0002c8048)
	/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000001b00)
	/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x8faea0, 0xc0002c8048)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/plgd-dev/device/test.MustFindDeviceIP(0xc0000d02d0, 0x12, 0x2, 0x0, 0x0)
	/go/src/github.com/plgd-dev/device/test/test.go:161 +0x139
github.com/plgd-dev/device/client/core_test.TestClientGetDeviceByIPWithIP6(0xc000001b00)
	/go/src/github.com/plgd-dev/device/client/core/getDevice_test.go:35 +0x85
testing.tRunner(0xc000001b00, 0x9667e0)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
```

Both times it succeeded when I triggered re-run. I see "cannot disown" messages in the test log, maybe it's related...?

**Review by jkralik — APPROVED** [review]

**Comment by jkralik** [comment]
> @jkralik for whatever reason this test sometimes fails, last time my PR was merged and it happened now:
> 
> ```
> --- FAIL: TestClientGetDeviceByIPWithIP6 (10.00s)
> panic: (Internal) no response from the device ef4bf406-4fcf-466b-49b9-6161abbf0fe4 [recovered]
> 	panic: (Internal) no response from the device ef4bf406-4fcf-466b-49b9-6161abbf0fe4
> 
> goroutine 65 [running]:
> testing.tRunner.func1.2(0x8faea0, 0xc0002c8048)
> 	/usr/local/go/src/testing/testing.go:1143 +0x332
> testing.tRunner.func1(0xc000001b00)
> 	/usr/local/go/src/testing/testing.go:1146 +0x4b6
> panic(0x8faea0, 0xc0002c8048)
> 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
> github.com/plgd-dev/device/test.MustFindDeviceIP(0xc0000d02d0, 0x12, 0x2, 0x0, 0x0)
> 	/go/src/github.com/plgd-dev/device/test/test.go:161 +0x139
> github.com/plgd-dev/device/client/core_test.TestClientGetDeviceByIPWithIP6(0xc000001b00)
> 	/go/src/github.com/plgd-dev/device/client/core/getDevice_test.go:35 +0x85
> testing.tRunner(0xc000001b00, 0x9667e0)
> 	/usr/local/go/src/testing/testing.go:1193 +0xef
> created by testing.(*T).Run
> 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
> ```
> 
> Both times it succeeded when I triggered re-run. I see "cannot disown" messages in the test log, maybe it's related...?

This happens when our device lib cannot find a device with the name via IPv6. Maybe this issue is created by our coap lib issues. I didn't yet release the new version.

**Comment by Danielius1922** [comment]
> This happens when our device lib cannot find a device with the name via IPv6. Maybe this issue is created by our coap lib issues. I didn't yet release the new version.
Maybe, but we should investigate it, if it keeps occurring after a new version of go-coap is released.

**Comment by jkralik** [comment]
@Danielius1922 There is a new test docker image released that contains a new go-coap and DTLS. I tested it three times and all tests pass.

**Review by ondrejtomcik — APPROVED** [review]

**Review by WAvdBeek — APPROVED** [review]

**Pull request merged**
