### PR TITLE
Fix bugs reported by SonarCloud

### PR DESCRIPTION
**Pull request by Danielius1922**

### CODE REVIEW

**Comment by Danielius1922** [comment]
~format

**Comment by SiMet** [comment]
@Danielius1922 I try to improve jenkins. Please do not start jobs today.

**Comment by Danielius1922** [comment]
> @Danielius1922 I try to improve jenkins. Please do not start jobs today.

I see, thanks for the heads up. I won't start any more OCF jobs today.

**Comment by SiMet** [comment]
> > @Danielius1922 I try to improve jenkins. Please do not start jobs today.
> 
> I see, thanks for the heads up. I won't start any more OCF jobs today.

@Danielius1922 I started last test. Quick tests looks fine.

Now, you should not see fail but PASSED_ON_RETRY. I added testcases as known issues:

```
known_issues = [
    "Client Certification": ["CT1.7.9.6.2", "CT1.7.9.6.3"],
    "Server Certification": ["CT1.7.9.6.2", "CT1.7.9.6.3"],
    "Onboarding Tool": ["CT3.1.9"]
]
```

You could run OCF tests if you'd like

**Comment by Danielius1922** [comment]
> @Danielius1922 I started last test. Quick tests looks fine.
> 
> Now, you should not see fail but PASSED_ON_RETRY. I added testcases as known issues:
> 
> ```
> known_issues = [
>     "Client Certification": ["CT1.7.9.6.2", "CT1.7.9.6.3"],
>     "Server Certification": ["CT1.7.9.6.2", "CT1.7.9.6.3"],
>     "Onboarding Tool": ["CT3.1.9"]
> ]
> ```
> 
> You could run OCF tests if you'd like

Thank you, I'll try it out then.

**Comment by Danielius1922** [comment]
~format

**Pull request merged**
