### PR TITLE
Refactoring of collection observation handling

### PR DESCRIPTION
**Pull request by Danielius1922**

### CODE REVIEW

**Comment by SiMet** [comment]
> @SiMet @ondrejtomcik there seems to be some issue with the starting of the OCF Conformance job, could someone please look into it? Thanks!

I look at this now.

**Comment by SiMet** [comment]
> > @SiMet @ondrejtomcik there seems to be some issue with the starting of the OCF Conformance job, could someone please look into it? Thanks!
> 
> I'm looking at this now.

One of job stuck due to restart machine over night. There was also issue in the script.
PR is now tested.

**Comment by SiMet** [comment]
@ondrejtomcik I see that labels are not removed. Could you look at this?

**Comment by ondrejtomcik** [comment]
> @ondrejtomcik I see that labels are not removed. Could you look at this?

I will, tomorrow. For bow just remove and assign label again.

**Review by jkralik — APPROVED** [review]

**Comment by jkralik** [comment]
Good job 👍

**Comment by SiMet** [comment]
I see that test 1.2.23 which tests Collection - UPDATE failed.

**Comment by Danielius1922** [comment]
> I see that test 1.2.23 which tests Collection - UPDATE failed.

I've found and fixed the problem.

**Review by jkralik — APPROVED** [review]

**Comment by jkralik** [comment]
@SiMet Pls could you check why `OCF Conformance / Test` is not executed? Thx

**Comment by SiMet** [comment]
> @SiMet Pls could you check why `OCF Conformance / Test` is not executed? Thx

It's waiting in queue. Already other commit is being tested (https://github.com/iotivity/iotivity-lite/actions/runs/2337586170). Test lasts about 3 hours and could not be executed parallelly

**Review by WAvdBeek — APPROVED** [review]

**Pull request merged**
