### PR TITLE
Bz2641 resource defaults

### PR DESCRIPTION
**Pull request by marktrayer**

### CODE REVIEW

**Comment by marktrayer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kmaloor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by WAvdBeek** [comment]
Mark, do we need this pull request?

**Comment by marktrayer** [comment]
> 
> 
> Mark, do we need this pull request?

Don't think so, I think we merged the code in a different PR.  Let me double check though.

**Comment by WAvdBeek** [comment]
already merged via jakarta

**Pull request closed without merging**
