### PR TITLE
[WIP] Introduce ctt test workflow

### PR DESCRIPTION
**Pull request by ondrejtomcik**

### CODE REVIEW

**Comment by Danielius1922** [comment]
@ondrejtomcik I think you have old submodules locally, there's a git command to upgrade the submodules from origin. The `deps/mbedtls` and `deps/tinycbor` changes should not be committed, I think that's the reason why all the tests fail.

**Comment by SiMet** [comment]
> @ondrejtomcik I think you have old submodules locally, there's a git command to upgrade the submodules from origin. The `deps/mbedtls` and `deps/tinycbor` changes should not be committed, I think that's the reason why all the tests fail.

I agree :)

**Review by SiMet — APPROVED** [review]

**Comment by ondrejtomcik** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ondrejtomcik** [comment]
recheck

**Pull request closed without merging**
