### PR TITLE
Add random PIN functionality to simpleserver

### PR DESCRIPTION
**Pull request by khaefner**
Simple server should implement Random PIN.  This PR implements that.

### CODE REVIEW

**Comment by khaefner** [comment]
The format errors check does not make sense to me...the code compiles and runs fine.

**Comment by SiMet** [comment]
~format

@khaefner I learn from @WAvdBeek that you could type ~format in comment and then bot will perform autoformating

**Comment by SiMet** [comment]
~format

**Comment by WAvdBeek** [comment]
https://github.com/iotivity/iotivity-lite/wiki/Code-style--&-Automatic-Formatting

**Pull request merged**
