### PR TITLE
Fix global coap status value

### PR DESCRIPTION
**Pull request by Danielius1922**
- remove the global variable from public header
- provide internal setter and getters
- fix issue when the status remained in CLOSE_ALL_TLS_SESSIONS state in some scenarios

### CODE REVIEW

**Review by jkralik — APPROVED** [review]

**Comment by Danielius1922** [comment]
Hello @SiMet, could you please check what's the issue with the CTT job? I've added the compilation command to GitHub jobs and it passed, so there must be some other issue. Thank you.

**Comment by SiMet** [comment]
> Hello @SiMet, could you please check what's the issue with the CTT job? I've added the compilation command to GitHub jobs and it passed, so there must be some other issue. Thank you.

Sure, but on Monday

**Comment by SiMet** [comment]
> > Hello @SiMet, could you please check what's the issue with the CTT job? I've added the compilation command to GitHub jobs and it passed, so there must be some other issue. Thank you.
> 
> Sure, but on Monday

@Danielius1922 test run is running. One machine required restart.

**Comment by Danielius1922** [comment]
> @Danielius1922 test run is running. One machine required restart.

Yes, everything seems to be in order. Thank you!

**Pull request merged**
