### PR TITLE
Fixes of compilations warning

### PR DESCRIPTION
**Pull request by SiMet**

### CODE REVIEW

**Comment by SiMet** [comment]
~format

**Review by Danielius1922 — APPROVED** [review]

**Comment by Danielius1922** [comment]
@SiMet Could you please check why the CTT job doesn't seem to start? However, these changes are minor so I can force merge this if you cannot wait.

**Comment by SiMet** [comment]
> @SiMet Could you please check why the CTT job doesn't seem to start? However, these changes are minor so I can force merge this if you cannot wait.

@Danielius1922 I fixed issue on jenkins and run it once again.

**Comment by Danielius1922** [comment]
> @Danielius1922 I fixed issue on jenkins and run it once again.

@SiMet: Thanks, indeed it's back to the state when just CT3.1.9, CT1.7.9.6.2 and CT1.7.9.6.3 cases are failing, so I'll merge this.

BTW will those test cases be fixed? If not then disabling them would make sense. Right now we always have a failure and then I check if the failures are just those three, in which case I ignore it and merge the PR anyway.

**Comment by SiMet** [comment]
> > @Danielius1922 I fixed issue on jenkins and run it once again.
> 
> @SiMet: Thanks, indeed it's back to the state when just CT3.1.9, CT1.7.9.6.2 and CT1.7.9.6.3 cases are failing, so I'll merge this.
> 
> BTW will those test cases be fixed? If not then disabling them would make sense. Right now we always have a failure and then I check if the failures are just those three, in which case I ignore it and merge the PR anyway.

We had mail exchange what should be done here. Eonti certificates which where required for this 3 testcases could not be generated. So test setup is not meet.

As I remmember we could dissable testcases 1.7.9.6.2 and 1.7.9.6.3 in PICS but 3.1.9 which tests two certs provider could not be dissabled

**Comment by Danielius1922** [comment]
@SiMet, yes I recall the conversation, it was back in November. you said that we are waiting for OCF. Is there anything new there? If a solution is still far away (several months), can't we come up with some sort of a quick solution in the wrapper .py script? Something like ignoring the failure if the failed test cases are those three -  1.7.9.6.2, 1.7.9.6.3 and 3.1.9?

**Pull request merged**
